version: 2.1
orbs:
  python: circleci/python@2.1.1
jobs:
  install_and_test:
    executor: python/default
    working_directory: ~/symeo-python-template
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests with coverage
          command: |
            poetry shell
            coverage run -m pytest tests
      - run:
          name: Display coverage
          command: |
            poetry shell
            coverage report

workflows:
  install_and_test:
    jobs:
      - install_and_test
