version: 2.1
orbs:
  python: circleci/python@2.1.1
  slack: circleci/slack@4.10.1

jobs:
  install_and_test:
    executor: python/default
    working_directory: ~/symeo-python-template
    machine: true
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests with coverage
          command: |
            poetry run coverage run -m pytest tests
      - run:
          name: Display coverage
          command: |
            poetry run coverage report
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  install_and_test:
    jobs:
      - install_and_test:
        context:
          - slack-notifications
