version: 2.1
orbs:
  python: circleci/python@2.1.1
  slack: circleci/slack@4.10.1
jobs:
  install_and_test:
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    working_directory: ~/symeo-python-template
    steps:
      - checkout
      - run:
          name: Install system dependencies
          command: |
            sudo apt update
            sudo apt install libpq-dev
            python3 -m pip install -U pip pipx
            python3 -m pipx install poetry
            python3 -m pipx ensurepath
      - run:
          name: Install project dependencies
          command: |
            poetry install
      - run:
          name: Run tests with coverage
          command: |
            poetry run coverage run -m pytest tests
      - run:
          name: Display coverage
          command: |
            poetry run coverage report
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  install_and_test:
    jobs:
      - install_and_test:
          context:
            - slack-notifications
